### ISSUE TITLE
possible regression and exception while handling link failures

### ISSUE THREAD

**Issue by italovalcy** [atlanticwave-sdx/sdx-controller#350]
Hi team,

While testing a link failure I got this exception below:

```
sdx-controller-1  | 2024-11-06T19:15:57.184862366Z INFO:sdx_pce.topology.temanager:generate_traffic_matrix, ports: ingress_port.id: urn:sdx:port:france.geant.org:geantFRS1:50, egress_port.id: urn:sdx:port:tenet.ac.za:tenetS1:50
sdx-controller-1  | 2024-11-06T19:15:57.184866594Z WARNING:sdx_pce.topology.temanager:No ingress node 'urn:sdx:node:france.geant.org:geantFRS1' found in the graph
sdx-controller-1  | 2024-11-06T19:15:57.184869104Z INFO:sdx_controller.handlers.connection_handler:Connection 1449c998-a41f-48c5-ae05-72fab1382e7c affected by link urn:sdx:link:interdomain:france.geant.org:geantFRS1:19:lhc.cern:lhcS1:19
sdx-controller-1  | 2024-11-06T19:15:57.215589498Z Exception in thread Thread-2:
sdx-controller-1  | 2024-11-06T19:15:57.215709422Z Traceback (most recent call last):
sdx-controller-1  | 2024-11-06T19:15:57.215722657Z   File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
sdx-controller-1  | 2024-11-06T19:15:57.216056951Z     self.run()
sdx-controller-1  | 2024-11-06T19:15:57.216064705Z   File "/usr/local/lib/python3.9/threading.py", line 917, in run
sdx-controller-1  | 2024-11-06T19:15:57.216240156Z     self._target(*self._args, **self._kwargs)
sdx-controller-1  | 2024-11-06T19:15:57.216251556Z   File "/opt/venv/lib/python3.9/site-packages/sdx_controller/messaging/rpc_queue_consumer.py", line 135, in start_sdx_consumer
sdx-controller-1  | 2024-11-06T19:15:57.232771334Z     lc_message_handler.process_lc_json_msg(
sdx-controller-1  | 2024-11-06T19:15:57.239629866Z   File "/opt/venv/lib/python3.9/site-packages/sdx_controller/handlers/lc_message_handler.py", line 46, in process_lc_json_msg
sdx-controller-1  | 2024-11-06T19:15:57.239652286Z     self.connection_handler.handle_link_failure(
sdx-controller-1  | 2024-11-06T19:15:57.239660823Z   File "/opt/venv/lib/python3.9/site-packages/sdx_controller/handlers/connection_handler.py", line 271, in handle_link_failure
sdx-controller-1  | 2024-11-06T19:15:57.239669017Z     self.remove_connection(te_manager, connection["id"])
sdx-controller-1  | 2024-11-06T19:15:57.239676367Z   File "/opt/venv/lib/python3.9/site-packages/sdx_controller/handlers/connection_handler.py", line 208, in remove_connection
sdx-controller-1  | 2024-11-06T19:15:57.239683897Z     te_manager.delete_connection(service_id)
sdx-controller-1  | 2024-11-06T19:15:57.239690657Z   File "/opt/venv/lib/python3.9/site-packages/sdx_pce/topology/temanager.py", line 1056, in delete_connection
sdx-controller-1  | 2024-11-06T19:15:57.272020121Z     self.update_link_bandwidth(solution, reduce=False)
sdx-controller-1  | 2024-11-06T19:15:57.272033951Z   File "/opt/venv/lib/python3.9/site-packages/sdx_pce/topology/temanager.py", line 383, in update_link_bandwidth
sdx-controller-1  | 2024-11-06T19:15:57.272150259Z     connectionRequest, links = self.get_links_on_path(solution)
sdx-controller-1  | 2024-11-06T19:15:57.272161264Z   File "/opt/venv/lib/python3.9/site-packages/sdx_pce/topology/temanager.py", line 360, in get_links_on_path
sdx-controller-1  | 2024-11-06T19:15:57.272290720Z     assert src_node is not None
sdx-controller-1  | 2024-11-06T19:15:57.272315700Z AssertionError
```

**Comment by italovalcy** [comment]
the topology I’m using is this one:
https://github.com/atlanticwave-sdx/sdx-sc24-demo

I was thinking maybe this is related to that old problem when we create L2VPNs on switches that are on the border of the OXP

In The scenario above , all OXP have only one switch

The connection request was this one:

```
curl -X POST -H 'Content-type: application/json' http://$SDX_CONTROLLER:8080/SDX-Controller/l2vpn/1.0 -d '{"name": "vlan from Tenet to France", "endpoints": [{"port_id": "urn:sdx:port:france.geant.org:geantFRS1:50", "vlan": "aby"}, {"port_id": "urn:sdx:port:tenet.ac.za:tenetS1:50", "vlan": "any"}]}'

$ $ curl http://$SDX_CONTROLLER:8080/SDX-Controller/l2vpn/1.0/29691d7c-9036-4687-8e85-d525392ba97a
{
  "29691d7c-9036-4687-8e85-d525392ba97a": {
    "archived_date": 0,
    "current_path": [
      {
        "port_id": "urn:sdx:port:france.geant.org:geantFRS1:50",
        "vlan": "4094"
      },
      {
        "port_id": "urn:sdx:port:france.geant.org:geantFRS1:19",
        "vlan": "4"
      },
      {
        "port_id": "urn:sdx:port:lhc.cern:lhcS1:19",
        "vlan": "4"
      },
      {
        "port_id": "urn:sdx:port:lhc.cern:lhcS1:16",
        "vlan": "4"
      },
      {
        "port_id": "urn:sdx:port:internet2.net:i2S1:16",
        "vlan": "4"
      },
      {
        "port_id": "urn:sdx:port:internet2.net:i2S1:14",
        "vlan": "4"
      },
      {
        "port_id": "urn:sdx:port:sax.net:saxS1:14",
        "vlan": "4"
      },
      {
        "port_id": "urn:sdx:port:sax.net:saxS1:12",
        "vlan": "4"
      },
      {
        "port_id": "urn:sdx:port:tenet.ac.za:tenetS1:12",
        "vlan": "4"
      },
      {
        "port_id": "urn:sdx:port:tenet.ac.za:tenetS1:50",
        "vlan": "4094"
      }
    ],
    "description": null,
    "endpoints": [
      {
        "port_id": "urn:sdx:port:france.geant.org:geantFRS1:50",
        "vlan": "4094"
      },
      {
        "port_id": "urn:sdx:port:tenet.ac.za:tenetS1:50",
        "vlan": "4094"
      }
    ],
    "name": "vlan test any--any",
    "service_id": "29691d7c-9036-4687-8e85-d525392ba97a"
  }
}
```

**Comment by congwang09** [comment]
Thanks Italo! Two questions:
The topology links to a `sdx-sc24-demo` repo, could you include the topology jsons, from each of the OXP going to the LCs?
What are the exact steps to reproduce the error? Were you trying to place a connection and then delete the connection after it's been placed?

**Comment by sajith** [comment]
@italovalcy @congwang09 I guess one problem here is that we have not replaced that `assert` in pce with an actual error check.  Using `assert` is fine and perhaps necessary during development, but not when actually running things.  We could simply log the event and move on.

Does this make sense as a solution?  Link failures (or anything else) could always carry incomplete data. Data validation failures should not crash us.

**Comment by sajith** [comment]
We could have simply set `PYTHONOPTIMIZE` or ran Python with `-O` flag in production (and kept `assert` statements for development), instead of "manually" removing the asserts.

https://docs.python.org/3/using/cmdline.html#cmdoption-O

But that probably is a more error-prone strategy, in case someone forgets to do that when deploying...
