### ISSUE TITLE
Internal server error while submitting a request with VLAN out of the allowed range

### ISSUE THREAD

**Issue by italovalcy** [atlanticwave-sdx/sdx-controller#356]
Hi,

Error while requesting a L2VPN with VLAN out of the allowed range from OXP:

```
$ curl -s -X POST -H 'Content-type: application/json' http://0.0.0.0:8090/SDX-Controller/l2vpn/1.0 -d '{"name": "VLAN between AMPATH/300 and TENET/300", "endpoints": [{"port_id": "urn:sdx:port:ampath.net:Ampath3:50", "vlan": "300"}, {"port_id": "urn:sdx:port:tenet.ac.za:Tenet03:50", "vlan": "any"}]}'
{
  "detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
  "status": 500,
  "title": "Internal Server Error",
  "type": "about:blank"
}
```

The topology used here is the same being used for [1]:
- https://github.com/atlanticwave-sdx/datamodel/blob/main/src/sdx_datamodel/data/topologies/ampath_v2.json
- https://github.com/atlanticwave-sdx/datamodel/blob/main/src/sdx_datamodel/data/topologies/sax_v2.json
- https://github.com/atlanticwave-sdx/datamodel/blob/main/src/sdx_datamodel/data/topologies/zaoxi_v2.json

The only difference from the topology above is that the vlan_range defined for the ports was more strict:

```
{"name":"Ampath-OXP","id":"urn:sdx:topology:ampath.net","version":12,"timestamp":"2024-11-13T18:04:13Z","model_version":"2.0.0","nodes":[{"name":"Ampath1","id":"urn:sdx:node:ampath.net:Ampath1","location":{"address":"Miami","latitude":25.77,"longitude":-80.19,"iso3166_2_lvl4":"US-FL","private":[]},"ports":[{"id":"urn:sdx:port:ampath.net:Ampath1:1","name":"Ampath1-eth1","node":"urn:sdx:node:ampath.net:Ampath1","type":"10GE","status":"up","state":"enabled","mtu":1500,"nni":"urn:sdx:link:ampath.net:Ampath1/1_Ampath2/1","services":{},"private":["status"]},{"id":"urn:sdx:port:ampath.net:Ampath1:40","name":"Ampath1-eth40","node":"urn:sdx:node:ampath.net:Ampath1","type":"10GE","status":"up","state":"enabled","mtu":1500,"nni":"urn:sdx:port:sax.net:Sax01:40","services":{"l2vpn-ptp":{"vlan_range":[[3000,3500]]}},"private":["status"]},{"id":"urn:sdx:port:ampath.net:Ampath1:2","name":"Ampath1-eth2","node":"urn:sdx:node:ampath.net:Ampath1","type":"10GE","status":"up","state":"enabled","mtu":1500,"nni":"urn:sdx:link:ampath.net:Ampath1/2_Ampath3/2","services":{},"private":["status"]},{"id":"urn:sdx:port:ampath.net:Ampath1:50","name":"Ampath1-eth50","node":"urn:sdx:node:ampath.net:Ampath1","type":"10GE","status":"up","state":"enabled","mtu":1500,"nni":"","services":{"l2vpn-ptp":{"vlan_range":[[100,199]]}},"private":["status"]}],"status":"up","state":"enabled"},{"name":"Ampath2","id":"urn:sdx:node:ampath.net:Ampath2","location":{"address":"BocaRaton","latitude":26.38,"longitude":-80.11,"iso3166_2_lvl4":"US-FL","private":[]},"ports":[{"id":"urn:sdx:port:ampath.net:Ampath2:1","name":"Ampath2-eth1","node":"urn:sdx:node:ampath.net:Ampath2","type":"10GE","status":"up","state":"enabled","mtu":1500,"nni":"urn:sdx:link:ampath.net:Ampath1/1_Ampath2/1","services":{},"private":["status"]},{"id":"urn:sdx:port:ampath.net:Ampath2:50","name":"Ampath2-eth50","node":"urn:sdx:node:ampath.net:Ampath2","type":"10GE","status":"up","state":"enabled","mtu":1500,"nni":"","services":{"l2vpn-ptp":{"vlan_range":[[100,199]]}},"private":["status"]},{"id":"urn:sdx:port:ampath.net:Ampath2:40","name":"Ampath2-eth40","node":"urn:sdx:node:ampath.net:Ampath2","type":"10GE","status":"up","state":"enabled","mtu":1500,"nni":"urn:sdx:port:sax.net:Sax02:40","services":{"l2vpn-ptp":{"vlan_range":[[3000,3500]]}},"private":["status"]},{"id":"urn:sdx:port:ampath.net:Ampath2:3","name":"Ampath2-eth3","node":"urn:sdx:node:ampath.net:Ampath2","type":"10GE","status":"up","state":"enabled","mtu":1500,"nni":"urn:sdx:link:ampath.net:Ampath2/3_Ampath3/3","services":{},"private":["status"]}],"status":"up","state":"enabled"},{"name":"Ampath3","id":"urn:sdx:node:ampath.net:Ampath3","location":{"address":"Jacksonville","latitude":30.27,"longitude":-81.68,"iso3166_2_lvl4":"US-FL","private":[]},"ports":[{"id":"urn:sdx:port:ampath.net:Ampath3:2","name":"Ampath3-eth2","node":"urn:sdx:node:ampath.net:Ampath3","type":"10GE","status":"up","state":"enabled","mtu":1500,"nni":"urn:sdx:link:ampath.net:Ampath1/2_Ampath3/2","services":{},"private":["status"]},{"id":"urn:sdx:port:ampath.net:Ampath3:50","name":"Ampath3-eth50","node":"urn:sdx:node:ampath.net:Ampath3","type":"10GE","status":"up","state":"enabled","mtu":1500,"nni":"","services":{"l2vpn-ptp":{"vlan_range":[[100,199]]}},"private":["status"]},{"id":"urn:sdx:port:ampath.net:Ampath3:3","name":"Ampath3-eth3","node":"urn:sdx:node:ampath.net:Ampath3","type":"10GE","status":"up","state":"enabled","mtu":1500,"nni":"urn:sdx:link:ampath.net:Ampath2/3_Ampath3/3","services":{},"private":["status"]}],"status":"up","state":"enabled"}],"links":[{"name":"Ampath1/1_Ampath2/1","id":"urn:sdx:link:ampath.net:Ampath1/1_Ampath2/1","ports":["urn:sdx:port:ampath.net:Ampath1:1","urn:sdx:port:ampath.net:Ampath2:1"],"type":"intra","bandwidth":10,"residual_bandwidth":100,"latency":0,"packet_loss":0,"availability":0,"status":"up","state":"enabled","private":["packet_loss"]},{"name":"Ampath2/3_Ampath3/3","id":"urn:sdx:link:ampath.net:Ampath2/3_Ampath3/3","ports":["urn:sdx:port:ampath.net:Ampath2:3","urn:sdx:port:ampath.net:Ampath3:3"],"type":"intra","bandwidth":10,"residual_bandwidth":100,"latency":0,"packet_loss":0,"availability":0,"status":"up","state":"enabled","private":["packet_loss"]},{"name":"Ampath1/2_Ampath3/2","id":"urn:sdx:link:ampath.net:Ampath1/2_Ampath3/2","ports":["urn:sdx:port:ampath.net:Ampath1:2","urn:sdx:port:ampath.net:Ampath3:2"],"type":"intra","bandwidth":10,"residual_bandwidth":100,"latency":0,"packet_loss":0,"availability":0,"status":"up","state":"enabled","private":["packet_loss"]}],"services":["l2vpn-ptp"]}
```

[1] https://sdx-docs.readthedocs.io/en/latest/sdx_deploy_single_server.html

**Comment by italovalcy** [comment]
The error on the SDX Logs is this:

```
sdx-controller  | ERROR:sdx_pce.topology.temanager:ingress_vlan: None, egress_vlan: 3003. Can't proceed. Rolling back reservations.
sdx-controller  | INFO:sdx_pce.topology.temanager:generate_connection_breakdown(): tagged_breakdown: None
sdx-controller  | ERROR:sdx_controller:Exception on /SDX-Controller/l2vpn/1.0 [POST]
sdx-controller  | Traceback (most recent call last):
sdx-controller  |   File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
sdx-controller  |     response = self.full_dispatch_request()
sdx-controller  |   File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
sdx-controller  |     rv = self.handle_user_exception(e)
sdx-controller  |   File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
sdx-controller  |     rv = self.dispatch_request()
sdx-controller  |   File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
sdx-controller  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
sdx-controller  |   File "/opt/venv/lib/python3.9/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
sdx-controller  |     response = function(request)
sdx-controller  |   File "/opt/venv/lib/python3.9/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
sdx-controller  |     response = function(request)
sdx-controller  |   File "/opt/venv/lib/python3.9/site-packages/connexion/decorators/validation.py", line 196, in wrapper
sdx-controller  |     response = function(request)
sdx-controller  |   File "/opt/venv/lib/python3.9/site-packages/connexion/decorators/parameter.py", line 120, in wrapper
sdx-controller  |     return function(**kwargs)
sdx-controller  |   File "/opt/venv/lib/python3.9/site-packages/sdx_controller/controllers/l2vpn_controller.py", line 141, in place_connection
sdx-controller  |     reason, code = connection_handler.place_connection(current_app.te_manager, body)
sdx-controller  | TypeError: cannot unpack non-iterable TEError object
```

**Comment by YufengXin** [comment]
In this case, PCE should throw an exception instead of returning None

added to the latest PR (though unrelated, sorry, Sajith):  https://github.com/atlanticwave-sdx/pce/pull/240

**Comment by italovalcy** [comment]
Hi Yufeng,

> In this case, PCE should throw an exception instead of returning None
> 
> added to the latest PR (though unrelated, sorry, Sajith): [atlanticwave-sdx/pce#240](https://github.com/atlanticwave-sdx/pce/pull/240)

Not sure if I understood, but I wonder how this exception raised by PCE will be handled on sdx-controller. Will you enhance this place_connection call to be handling exceptions?

**Comment by sajith** [comment]
@italovalcy @YufengXin The source of the problem is here:

https://github.com/atlanticwave-sdx/sdx-controller/blob/4855ca1b4ec010b4092114a08b8f64569965409b/sdx_controller/handlers/connection_handler.py#L170-L171

Line 171 should return an error string and error code.  It would be also useful if PCE could use `TEError` instead of just `None` to indicate failures.

I will work on a fix.

**Comment by YufengXin** [comment]
That's what I modified in PCE: raising a TEError instead of returning None. 
connection_handler would catch this exception and return the error.
TEError has both error_msg and the error code.

**Comment by sajith** [comment]
@italovalcy This is actually interesting:

```
ERROR:sdx_pce.topology.temanager:ingress_vlan: None, egress_vlan: 3003. Can't proceed. Rolling back reservations.
```

It appears that `ingress_vlan` become `None` when it should be 300.  Do we have PCE logs before that happened?

**Comment by sajith** [comment]
@italovalcy Wait, I have this (from running tests locally):

```
INFO     sdx_pce.topology.temanager:temanager.py:991 tag is not None, using the tag: 30000
ERROR    sdx_pce.topology.temanager:temanager.py:1007 VLAN 30000 is not present in the table
INFO     sdx_pce.topology.temanager:temanager.py:989 tag is None, using the upstream_egress_vlan: 1
ERROR    sdx_pce.topology.temanager:temanager.py:800 ingress_vlan: None, egress_vlan: 1. Can't proceed. Rolling back reservations.
INFO     sdx_pce.topology.temanager:temanager.py:612 generate_connection_breakdown(): tagged_breakdown: None
```

This was the PCE issue @YufengXin  fixed, I believe.
